name: 'shinnytech-oss-upload'
description: '上传项目文件到阿里云 shinny-cd'
inputs:
  upload-from-dir:
    description: "上传的目录"
    required: true
  upload-target:
    description: "上传的目标项目地址"
    required: true
  access-key-id:
    description: "AccessKeyID"
    required: true
  access-key-secret:
    description: "AccessKeySceret"
    required: true
  endpoint:
    description: "填写Bucket所在地域的域名信息，可参考访问域名和数据中心。默认为 oss-accelerate.aliyuncs.com"
    required: false
    default: "oss-accelerate.aliyuncs.com"
runs:
  using: "composite"
  steps:
    - run: |
        if [[ $GITHUB_REF_TYPE == 'tag' ]]; then
          DEST_DIR="$(echo ${GITHUB_REF##*/})/"
        elif [[ "$GITHUB_EVENT_NAME" == 'pull_request' ]]; then
          # 从事件 payload 读取 PR 源头分支和 commit，避免 composite 中 GITHUB_HEAD_SHA 未注入
          PR_HEAD_REF=$(jq -r '.pull_request.head.ref // empty' "$GITHUB_EVENT_PATH")
          PR_HEAD_SHA=$(jq -r '.pull_request.head.sha // empty' "$GITHUB_EVENT_PATH")
          PR_HEAD_REF="${PR_HEAD_REF:-$GITHUB_HEAD_REF}"
          PR_HEAD_REF="${PR_HEAD_REF##*/}"
          PR_HEAD_SHA="${PR_HEAD_SHA:-${GITHUB_HEAD_SHA:-$GITHUB_SHA}}"
          DEST_DIR="${PR_HEAD_REF}/$(echo ${PR_HEAD_SHA:0:7})/"
        else
          DEST_DIR="$(echo ${GITHUB_REF##*/})/$(echo ${GITHUB_SHA:0:7})/"
        fi
        echo "DEST_DIR=$DEST_DIR" >> $GITHUB_ENV
        echo "DEST_DIR is $DEST_DIR"
      shell: bash
    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-accelerate.aliyuncs.com"
        access-key-id: ${{inputs.access-key-id}}
        access-key-secret: ${{inputs.access-key-secret}}
    - run: ossutil cp -rf --recursive ${{inputs.upload-from-dir}} oss://shinny-cd/${{inputs.upload-target}}/${{env.DEST_DIR}}
      shell: bash
